# Generated by Django 4.2.16 on 2024-10-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('french', models.CharField(max_length=150)),
                ('english', models.CharField(max_length=150)),
                ('howmanytime', models.IntegerField(default=0)),
            ],
        ),
    ]
