# Generated by Django 4.2.16 on 2024-10-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
